find_package(PkgConfig QUIET)
pkg_check_modules(PC_LIBUSB QUIET libusb)

find_path(LIBUSB_INCLUDE_DIRS
  NAMES libusb.h
  HINTS ${LIBUSB_DIR}/include ${LIBUSB_DIR}/include/libusb-1.0 ${PC_LIBUSB_INCLUDE_DIRS})

find_library(LIBUSB_LIBRARIES
  NAMES libusb-1.0 usb-1.0
  HINTS ${LIBUSB_DIR}/lib ${PC_LIBUSB_LIBRARY_DIRS})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibUSB DEFAULT_MSG LIBUSB_LIBRARIES LIBUSB_INCLUDE_DIRS)

if(LIBUSB_FOUND AND NOT TARGET LibUSB)
  add_library(LibUSB UNKNOWN IMPORTED)
  set_target_properties(LibUSB PROPERTIES
	IMPORTED_LINK_INTERFACE_LANGUAGES "C"
	IMPORTED_LOCATION "${LIBUSB_LIBRARIES}"
	INTERFACE_INCLUDE_DIRECTORIES "${LIBUSB_INCLUDE_DIRS}")
endif()
